### ISSUE TITLE
Explain Delta Generator

### ISSUE THREAD

**Issue by Immortalin** [mattbaker/git-vanity-sha#1]
Hi! Would you mind explaining how the delta generation works? The bitshifts are a bit confusing.

**Comment by s7726** [comment]
It's Ruby, they aren't bit shifts
https://stackoverflow.com/a/6852104/1006048

**Comment by misternu** [comment]
The Enumerator generates alternating positive and negative integers up to the number of seconds that elapses in 10 days (` 0,0,1,-1,2,-2,3,-3...`). `<<` is an alias for `yield`.
