### ISSUE TITLE
Leetspeak workaround for difficult words

### ISSUE THREAD

**Issue by misternu** [mattbaker/git-vanity-sha#4]
Some words that would be invalid could be made to work by using number substitutes for some letters, example:

'leet' => ['1337', '1ee7']

And some valid words could be tried in multiple spellings to decrease the error being introduced to the commit time, or to provide options:

'cafe' => ['cafe', 'c4fe', 'caf3', c4f3']

**Comment by mattbaker** [comment]
This is a cool idea, let's keep it in mind :)
