### ISSUE TITLE
Doesn't work with signed commits

### ISSUE THREAD

**Issue by aveao** [mattbaker/git-vanity-sha#5]
This is more of a git limitation than anything, but I feel like it should be noted down in README or smth that you need to disable commit signing for this to work (`git config commit.gpgsign false`).

See below for an issue caused by this:

![](https://use.elixi.re/i/cv3.png)

**Comment by mattbaker** [comment]
A PR to the README would be welcome :)

Any idea why it doesn't work? I don't know much about commit signing.

**Comment by ghost** [comment]
You need to modify the raw commit instead of the committer. If I have the time, I might do a PR.

**Comment by AnthonyMastrean** [comment]
@alex-mohemian what do you mean "modify the raw commit"?

**Comment by ghost** [comment]
@AnthonyMastrean this tool does a simple `git commit --amend --no-edit`, so it merely modifies the committer.

You can update the raw commit with `git update-ref HEAD <commit>` which would allow signed commits but might break something in the future: https://git-scm.com/docs/git-update-ref

**Comment by graingert** [comment]
If you use ed25519 I think there's no need to modify the commit, as you can roll the elliptic curve nonce
